name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
          sudo dpkg -i pandoc-2.19.2-1-amd64.deb
          sudo apt-get install -f
          python -m pip install --upgrade pip setuptools
          pip install -e '.[dev]'
          npm install -g @mermaid-js/mermaid-cli@9.4.0
          mmdc --version

      - name: Run tests
        run: |
          flake8 .
          pytest tests
