name: Test
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb
          sudo dpkg -i pandoc-2.16.2-1-amd64.deb
          sudo apt-get install -f
          python -m pip install --upgrade pip setuptools
          pip install -e '.[dev]'
      - name: Run tests
        run: |
          flake8 .
          pytest tests
